inno-Doctor/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

inno-Doctor/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('patient_records/', include('patient_records.urls')),
    path('patient_records/', include('patient_records.apiurls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inno-Doctor/patient_records/urls.py
from django.urls import path
from . import views
from .models import Patient
app_name = 'patient_records'

urlpatterns = [
    
    path('patient-check', views.patientCheck, name='patient_check'),
    path('patient-details/',views.patientDetails, name ='patient_details'),
    path('patient-create/', views.patientCreate, name='patient_create'),
    path('patient-detail/<int:id>',views.patientDetail, name ='patient_detail'),
    path('patient-update/<int:id>', views.patientUpdate, name='patient_update'),
    
    path('patient-problem-list-create/<int:id>', views.patientProblemListCreate, name='patient_problem_list_create'),
    path('patient-problem-list-view/<int:id>', views.patientProblemListView, name='patient_problem_list_view'),
    
    path('patient-social-history-create/<int:id>', views.patientSocialHistoryCreate, name='patient_social_histroy_create'),
    path('patient-social-history-view/<int:id>', views.patientSocialHistoryView, name='patient_social_histroy_view'),
    path('patient-social-history-edit/<int:id>', views.patientSocialHistoryUpdate, name='patient_social_histroy_update'),
   
    path('patient-vital-sign-create/<int:id>', views.patientVitalSignCreate, name='patient_vital_sign_create'),
    path('patient-vital-sign-view/<int:id>', views.patientVitalSignView, name='patient_vital_sign_view'),
    path('patient-vital-sign-edit/<int:id>', views.patientVitalSignUpdate, name='patient_vital_sign_edit'),
   
    path('patient-eprescription/<int:id>', views.eprescriptionList, name='eprescription'),
    path('patient-eprescription-create/<int:id>', views.eprescriptionCreate, name='eprescription-create'),
    path('patient-medication-statement/<int:id>', views.medicationStatementCreate, name='add_new_patient_medication_statement_by_POST'),

    path('patient_record_form/', views.PatientView, name='patient_record_form'),
    path('patient_record_list/', views.PatientList, name='patient_record_list'),
    
]

inno-Doctor/content/templates/layouts/default/_footer.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
<footer class="footer pt-5 mt-5">
    <div class="container">
      <div class=" row">
        <div class="col-md-3 mb-4 ms-auto">
          <div>
            <a href="https://www.creative-tim.com/product/material-kit">
              <img src="{% static 'img/logo-ct-dark.png' %}" class="mb-3 footer-logo" alt="main_logo">
            </a>
            <h6 class="font-weight-bolder mb-4">Material Kit 2</h6>
          </div>
          <div>
            <ul class="d-flex flex-row ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.facebook.com/CreativeTim" target="_blank">
                  <i class="fab fa-facebook text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://twitter.com/creativetim" target="_blank">
                  <i class="fab fa-twitter text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://dribbble.com/creativetim" target="_blank">
                  <i class="fab fa-dribbble text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                  <i class="fab fa-github text-lg opacity-8"></i>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link pe-1" href="https://www.youtube.com/channel/UCVyTG4sCw-rOvB9oHkzZD1w" target="_blank">
                  <i class="fab fa-youtube text-lg opacity-8"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Company</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/presentation" target="_blank">
                  About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/free" target="_blank">
                  Freebies
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/templates/premium" target="_blank">
                  Premium Tools
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/blog" target="_blank">
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Resources</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://iradesign.io/" target="_blank">
                  Illustrations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/bits" target="_blank">
                  Bits & Snippets
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/affiliates/new" target="_blank">
                  Affiliate Program
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4">
          <div>
            <h6 class="text-sm">Help & Support</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/contact-us" target="_blank">
                  Contact Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center" target="_blank">
                  Knowledge Center
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://services.creative-tim.com/?ref=ct-mk2-footer" target="_blank">
                  Custom Development
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/sponsorships" target="_blank">
                  Sponsorships
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
          <div>
            <h6 class="text-sm">Legal</h6>
            <ul class="flex-column ms-n3 nav">
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center/terms-of-service" target="_blank">
                  Terms & Conditions
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/knowledge-center/privacy-policy" target="_blank">
                  Privacy Policy
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.creative-tim.com/license" target="_blank">
                  Licenses (EULA)
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-12">
          <div class="text-center">
            <p class="text-dark my-4 text-sm font-weight-normal">
              All rights reserved. Copyright © <script>
                document.write(new Date().getFullYear())
              </script> Material Kit by <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
            </p>
          </div>
        </div>
      </div>
    </div>
  </footer>

inno-Doctor/content/templates/layouts/default/_navbar.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg  blur border-radius-xl top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
  <div class="container-fluid px-0">
    <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" data-placement="bottom">
      InnoDoctor
    </a>
    <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon mt-2">
        <span class="navbar-toggler-bar bar1"></span>
        <span class="navbar-toggler-bar bar2"></span>
        <span class="navbar-toggler-bar bar3"></span>
      </span>
    </button>
    <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
      <ul class="navbar-nav navbar-nav-hover ms-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item ms-lg-auto">
            <a class="nav-link nav-link-icon me-2" href="{% url 'patient_records:patient_check' %}">
              <i class="fas fa-stethoscope" aria-hidden="true"></i>
              <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Modify Patient Record">Check Patient</p>
            </a>
          </li>

          <li class="nav-item ms-lg-auto">
            <a class="nav-link nav-link-icon me-2" href="{% url 'patient_records:patient_create' %}">
              <i class="fas fa-plus-circle" aria-hidden="true"></i>
              <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Add New Patient Record">Add Patient</p>
            </a>
          </li>

        <li class="nav-item dropdown dropdown-hover mx-2">
          <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
            Profile
            <img src="{% static 'img/down-arrow-dark.svg' %} " alt="down-arrow" class="arrow ms-auto ms-md-2">
          </a>
          <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
            <div class="d-none d-lg-block">
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                Edit Profile
              </h6>
              <a href="{% url 'accounts:change_password' %}" class="dropdown-item border-radius-md">
                <span>Change Password</span>
              </a>
              <a href="{% url 'accounts:change_profile' %}" class="dropdown-item border-radius-md">
                <span>Change Name</span>
              </a>
              <a href="{% url 'accounts:change_email' %}" class="dropdown-item border-radius-md">
                <span>Change Email</span>
              </a>
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                Actions
              </h6>
              <a href="{% url 'accounts:log_out' %}" class="dropdown-item border-radius-md">
                <span>Logout</span>
              </a>
            </div>
            <div class="d-lg-none">
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                Edit Profile
              </h6>
              <a href="{% url 'accounts:change_password' %}" class="dropdown-item border-radius-md">
                <span>Change Password</span>
              </a>
              <a href="{% url 'accounts:change_profile' %}" class="dropdown-item border-radius-md">
                <span>Change Name</span>
              </a>
              <a href="{% url 'accounts:change_email' %}" class="dropdown-item border-radius-md">
                <span>Change Email</span>
              </a>
              <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                Actions
              </h6>
              <a href="{% url 'accounts:log_out' %}" class="dropdown-item border-radius-md">
                <span>Logout</span>
              </a>
            </div>
          </div>
        </li>
        {% endif %}
        <li class="nav-item ms-lg-auto">
          <a class="nav-link nav-link-icon me-2" href="https://github.com/sha-since1999/inno-doctor" target="_blank">
            <i class="fa fa-github me-1"></i>
            <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Star us on Github">Github</p>
          </a>
        </li>
        <li class="nav-item ms-lg-auto">
          <a class="nav-link nav-link-icon me-2" href="{% url 'change_language' %}">
            <i class="fas fa-language"></i>
            <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Switch Language">Languages</p>
          </a>
        </li>
        {% if not request.user.is_authenticated %}
        <li class="nav-item my-auto ms-3 ms-lg-0">
          <a href="{% url 'accounts:log_in' %}" class="btn btn-sm  bg-gradient-info  mb-0 me-1 mt-2 mt-md-0">Doctor Login</a>
        </li>
        <li class="nav-item my-auto ms-3 ms-lg-0">
          <a href="{% url 'patient_records:patient_record_form' %}" class="btn btn-sm  bg-gradient-primary  mb-0 me-1 mt-2 mt-md-0">Continue as Patient</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

inno-Doctor/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}>
  <link rel="icon" href="{% static 'img/favicon.png' %}">

  <title>
    {% if title %}
      InnoDoctor - {{title}}
    {% else %}
      InnoDoctor
    {% endif %}
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-kit.css' %}" rel="stylesheet" />

</head>

<body class="presentation-page bg-gray-200">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        {% block navbar %}
          {% include 'layouts/default/_navbar.html' %}
        {% endblock %}
      </div>
    </div>
  </div>

<!--  {% if messages %}-->
<!--      <div class="container position-fixed top-20">-->
<!--            <div class="row">-->
<!--              {% for message in messages %}-->
<!--                <div class="alert alert-info alert-dismissible fade show text-white font-weight-bold text-center mx-auto h-1" role="alert">-->
<!--                  {{ message }}-->
<!--                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">x</button>-->
<!--                </div>-->
<!--              {% endfor %}-->
<!--            </div>-->
<!--  {% endif %}-->

  {% block header %}
    <header class="header-2">
      <div class="page-header min-vh-75 relative" style="background-image: url('{% static "img/b.jpg" %}')">
          <span class="mask bg-gradient-info opacity-6"></span>
          <div class="container">
            <div class="row">
              <div class="col-lg-7 text-center mx-auto">
                {% if heading %}
                  <h1 class="text-white pt-3 mt-n5">{{heading}}</h1>
                {% else %}
                  <h1 class="text-white pt-3 mt-n5">InnoDoctor</h1>
                {% endif %}

                {% if subheading %}
                <p class="lead text-white mt-3">{{subheading}}</p>
                {% else %}
                  <p class="lead text-white mt-3">Create and Maintain Patient Records and Prescriptions<br /> Trusted by over 1.6 million doctors around the world. </p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
  </header>
  {% endblock %}

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    {% block content %}
    {% endblock %}
  </div>

  {% include 'layouts/default/_footer.html' %}

  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{% static 'js/plugins/countup.min.js' %}"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{% static 'js/plugins/rellax.min.js' %}"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{% static 'js/plugins/tilt.min.js' %}"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{% static 'js/plugins/choices.min.js' %}"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{% static 'js/plugins/parallax.min.js' %}"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{% static 'js/material-kit.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/kit-free.js' %}" type="text/javascript"></script>
  {% block script %}
  {% endblock %}
</body>

</html>

inno-Doctor/content/templates/layouts/default/page_backup.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as language_code %}

<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="An example of Django project with basic user functionality.">
    <meta name="author" content="Yehor Smoliakov">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <title>{% block title %} InnoDoctor{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <style>
        body{
            background-color: #8EB4D4;

        }
        
            .page-footer{
              position: fixed;
           left:0px;
           bottom:0px;
           width:100%;
          background-color : grey;
          
            }

        </style> 

</head>


<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'InnoDoctor' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patient_records:patient_check' %}">{% trans 'Check Patient' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'patient_records:patient_create' %}">{% trans 'Add Patient' %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Profile
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Change Password</a>
                      <a class="dropdown-item" href="{% url 'accounts:change_profile' %}">Change Profile</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'accounts:change_email' %}">Change Email</a>
                    </div>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                </li>

            {% else %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li>
                
            {% endif %}
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'change_language' %}">{% trans 'Language' %}</a>
            </li>
        </ul>
    </div>

</nav>

<div class="container-fluid mt-3 img-responsive"    >

    {% bootstrap_messages %}
    
    {% block content %}
        No content.

    {% endblock %}
    

</div>

<footer class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2022 Copyright:
      <a href="#"> InnoDoctor.com</a>
    </div>
    <!-- Copyright -->

  </footer>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>