inno-Doctor/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
    path('patient_records/', include('patient_records.urls')),
    path('patient_records/', include('patient_records.apiurls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inno-Doctor/patient_records/urls.py
from django.urls import path
from . import views
from .models import Patient
app_name = 'patient_records'

urlpatterns = [
    
    path('patient-check', views.patientCheck, name='patient_check'),
    path('patient-details/',views.patientDetails, name ='patient_details'),
    path('patient-create/', views.patientCreate, name='patient_create'),
    path('patient-detail/<int:id>',views.patientDetail, name ='patient_detail'),
    path('patient-update/<int:id>', views.patientUpdate, name='patient_update'),
    
    path('patient-problem-list-create/<int:id>', views.patientProblemListCreate, name='patient_problem_list_create'),
    path('patient-problem-list-view/<int:id>', views.patientProblemListView, name='patient_problem_list_view'),
    
    path('patient-social-history-create/<int:id>', views.patientSocialHistoryCreate, name='patient_social_histroy_create'),
    path('patient-social-history-view/<int:id>', views.patientSocialHistoryView, name='patient_social_histroy_view'),
    path('patient-social-history-edit/<int:id>', views.patientSocialHistoryUpdate, name='patient_social_histroy_update'),
   
    path('patient-vital-sign-create/<int:id>', views.patientVitalSignCreate, name='patient_vital_sign_create'),
    path('patient-vital-sign-view/<int:id>', views.patientVitalSignView, name='patient_vital_sign_view'),
    path('patient-vital-sign-edit/<int:id>', views.patientVitalSignUpdate, name='patient_vital_sign_edit'),
   
    path('patient-eprescription/<int:id>', views.eprescriptionList, name='eprescription'),
    path('patient-eprescription-create/<int:id>', views.eprescriptionCreate, name='eprescription-create'),
    path('patient-medication-statement/<int:id>', views.medicationStatementCreate, name='add_new_patient_medication_statement_by_POST'),

    path('patient_record_form/', views.PatientView, name='patient_record_form'),
    path('patient_record_list/', views.PatientList, name='patient_record_list'),
    
]

inno-Doctor/patient_records/forms.py
from django.forms import ModelForm, DateField
import datetime
from .models import (MedicationItem, Patient,
                     ProblemList,
                     VitalSign, SocialHistory, MedicationStatement, )
from django.forms.models import inlineformset_factory

class PatientForm(ModelForm):
    # date_of_birth = DateField(initial=datetime.date.today) 
    class Meta:
        model = Patient
        fields = ['aadhaarId', 'name', 'gender', 'date_of_birth']
        # widgets = {'date_of_birth': DateField(datetime.date.today)}
        
class MedicationItemForm(ModelForm):
    class Meta:
        model = MedicationItem
        fields = '__all__'
        
    # def __init__(self, *args, **kwargs):
    #     """Populating the choices of  the favorite_choices field using the favorites_choices kwargs"""
    #     favorites_choices = kwargs.pop('medication_item')
    #     super().__init__(*args, **kwargs)
    #     self.fields['medication_item'].choices = favorites_choices

class MedicationStatementForm(ModelForm):
    class Meta:
        model = MedicationStatement
        fields = ("patient",)
        
class ProblemListForm(ModelForm):

    class Meta:
        model = ProblemList
        fields = ['problem', 'body_site', 'severity', 'abatement_date', 'diagnostic_certainty',]
        
class SocialHistoryForm(ModelForm):
    
    class Meta:
        model = SocialHistory
        fields = ['tobacco_smoking_status', 'alcohol_consumption_status', 'alcohol_consumption_unit', 'alcohol_consumption_frequency']

class VitalSignForm(ModelForm):
    
    class Meta:
        model = VitalSign
        fields = {'body_weight',
                'height',
                'respiration_rate',
                'pulse_rate',
                'body_temperature',
                'head_circumference',
                'pulse_oximetry',
                'body_mass_index',
                'blood_pressure_systolic',
                'blood_pressure_diastolic' 
                }
        


MedicationStatementFormSet = inlineformset_factory(MedicationStatement, 
                                                       MedicationItem, 
                                                       fields=(
                                                           'medication_item', 
                                                           'name', 
                                                           'form', 
                                                           'category', 
                                                           'unit_of_prescription', 
                                                           'batch_id', 
                                                           'expiry',
                                                           'dose_amount',
                                                           'dose_duration',
                                                           'dose_unit', 
                                                           'dose_frequency',
                                                           'dose_interval',
                                                           'dose_specific_timing',
                                                           'route',
                                                           'body_site'
                                                       ),
                                                        extra=5
                                                   )

inno-Doctor/patient_records/views.py
from email.message import Message
from django.http.response import HttpResponse
from django.shortcuts import render, get_object_or_404, render_to_response
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.urls import reverse

from django.shortcuts import  redirect
from .models import Patient

from django.shortcuts import render

from .forms import (MedicationItemForm, PatientForm,
                    SocialHistoryForm,VitalSignForm,
                     ProblemListForm,
                      MedicationStatementForm, MedicationStatementFormSet
                    )

from .models import (MedicationItem, Patient,
                     ProblemList,
                     VitalSign, SocialHistory, MedicationStatement, )


from django.contrib import messages
from django.forms.models import inlineformset_factory


# Create your views here.
def eprescriptionList(request, id):  
    patient = Patient.objects.get(aadhaarId=id)
   
    # medicationStatements=get_object_or_404(MedicationStatement, patient=patient)
    medicationstatements=MedicationStatement.objects.filter(patient=patient)
    # print(medicationstatements)
    medicationitems={}
    # medication_statement_ids=[]
    for medicationstatement in medicationstatements:
        medicationitem = MedicationItem.objects.filter(medication_statement=medicationstatement)
        # print(medicationitem)
        # medication_statement_ids.append(medicationstatement.id)
        if medicationitem is not None:
            medicationitems[medicationstatement.id] = medicationitem
    # print(medicationitems.items())
    for a, b in medicationitems.items():
        print(a)
        for x in b:
            print(x.name)
    context = {"medicationitems": medicationitems, 'aadhaarId': id}
    return render(request,"patient_records/eprescription.html" , context=context)
    # except:
    #         messages.error(request, 'no medication statemtment found!') 
    return  redirect('/patient_records/patient-detail/{}'.format(id))  

def patientDetails(request):

    if request.method == "POST":  
        try:
            id= request.POST['aadhaarId']
            patient= get_object_or_404(Patient,aadhaarId=id)
            return render(request,"patient_records/patient-details.html",context={'patient':patient})  
        except:
            messages.error(request, 'patient record not found')
    return redirect('/patient_records/patient-check')  
         
         
def patientDetail(request , id)  : 
    try:
        patient= get_object_or_404(Patient,aadhaarId=id)
        return render(request,"patient_records/patient-details.html",context={'patient':patient})  
    except:
        messages.error(request, 'patient record found')
        
    return redirect('/patient_records/patient-check')  

        
def patientCheck(request):  
    patients = Patient.objects.all()  
    return render(request , "patient_records/patient-check.html",{'patients':patients})  

def patientCreate(request):  
    if request.method == "POST":  
        form = PatientForm(request.POST)  
        id= request.POST['aadhaarId']
        if form.is_valid():  
            try:  
                form.save() 
                messages.success(request, 'New Patient is successfully added.!')
                model = form.instance
                return  redirect('/patient_records/patient-detail/{}'.format(id))  
            except:  
                messages.error(request, 'failed to add patient')
    else:  
        form = PatientForm()  
    return render(request,'patient_records/patient-create.html',{'form':form})  

def patientUpdate(request, id):  
    patient = Patient.objects.get(aadhaarId=id)
    form = PatientForm(initial={'name': patient.name, 'aadhaarId': patient.aadhaarId, 'date_of_birth': patient.date_of_birth, 'gender': patient.gender})
    if request.method == "POST":  
        form = PatientForm(request.POST, instance=patient)  
        if form.is_valid():  
            try:  
                form.save() 
                # model = form.instance
                messages.success(request,'patient updated!')
                return redirect('/patient_records/patient-check')  
            except Exception as e: 
                messages.error(request,'update error!')
    return render(request,'patient_records/patient-update.html',{'form':form})  


def PatientView(request):
    return render(request, "patient_records/patient_record_form.html")

def PatientList(request):
    aadhaarId = request.POST.get('aadharid')
    date_of_birth=request.POST.get('bdate')
    if (Patient.objects.filter(aadhaarId=aadhaarId).exists()) and (Patient.objects.filter(date_of_birth=date_of_birth).exists()):
        # ips_id = Patient.objects.get(
        #         aadhaarId = aadhaarId
        # ).id
        medication_id = MedicationStatement.objects.filter(
                patient_id = aadhaarId
        ).values_list('id', flat = True).order_by(
                '-timestamp')[:1]
        medication_items = MedicationItem.objects.filter(
                medication_statement_id=medication_id)
        my_values = [item.dose_amount for item in medication_items]
        args = {'medication_items': medication_items }
        return render(request, "patient_records/patient_record_list.html", args)
    else:
        # messages.error(request, 'Patient is not registered')
        return render(request, "patient_records/patient_record_form.html")



def patientProblemListCreate(request , id):
    patient= Patient.objects.get(aadhaarId=id)
    
    if request.method == "POST":  
        form = ProblemListForm(request.POST, initial={ 'patient':patient })  
        if form.is_valid():  
            try:  
                obj=form.save(commit=False)
                obj.patient =Patient.objects.get(aadhaarId=id)
                obj.save()
                messages.success(request, 'New Problem is successfully added to the problem list!')
                # model = form.instance
                return  redirect('/patient_records/patient-detail/{}'.format(id))   
            except:  
                messages.error(request, 'Failed to add problem to the problem list')
    else:  
        form = ProblemListForm( initial={ 'patient':patient } )  
    return render(request,'patient_records/patient-problem-list.html',{'form':form,'patient' :patient})  

def patientSocialHistoryCreate(request , id):
    patient= Patient.objects.get(aadhaarId=id)
    try:
        social_history = SocialHistory.objects.get(patient=patient)
    except:
        social_history = None
    if social_history:
        messages.error(request, 'Social History record already exists')
        return redirect('/patient_records/patient-detail/{}'.format(id))
    if request.method == "POST":  
        form = SocialHistoryForm(request.POST, initial={ 'patient':patient })  
        if form.is_valid():  
            try:  
                obj=form.save( commit=False) 
                obj.patient =Patient.objects.get(aadhaarId=id)
                obj.save()
                messages.success(request, 'New Social History is successfully added.!')
                # model = form.instance
                return  redirect('/patient_records/patient-detail/{}'.format(id)) 
            except:  
                messages.error(request, 'failed to add Social History list')
    else:  
        form = SocialHistoryForm( initial={ 'patient':patient } )  
    return render(request,'patient_records/patient-social-history-list.html',{'form':form,'patient' :patient})  

def patientVitalSignCreate(request , id):
    patient= Patient.objects.get(aadhaarId=id)
    try:
        vital_sign = VitalSign.objects.get(patient=patient)
    except:
        vital_sign = None
    if vital_sign:
        messages.error(request, 'Vital Signs records already exists')
        return redirect('/patient_records/patient-detail/{}'.format(id))
    if request.method == "POST":  
        form = VitalSignForm(request.POST, initial={ 'patient':patient })  
        if form.is_valid():  
            try:  
                obj=form.save( commit=False) 
                obj.patient =Patient.objects.get(aadhaarId=id)
                obj.save()
                messages.success(request, 'New Vital Sign is successfully added.!')
                # model = form.instance
                return  redirect('/patient_records/patient-detail/{}'.format(id)) 
            except:  
                messages.error(request, 'failed to add vital sign')
    else:  
        form = VitalSignForm( initial={ 'patient':patient } )  
    return render(request,'patient_records/patient-vital-sign.html',{'form':form,'patient' :patient})  


def patientSocialHistoryUpdate(request , id):
    patient= Patient.objects.get(aadhaarId=id)
    socialhistory= SocialHistory.objects.get(patient=patient)
    form= SocialHistoryForm( initial = {'patient':patient, 'tobacco_smoking_status':socialhistory.tobacco_smoking_status,'alcohol_consumption_status':socialhistory,'alcohol_consumption_unit':socialhistory.alcohol_consumption_unit, 'alcohol_consumption_frequency':socialhistory.alcohol_consumption_frequency} )
    if request.method == "POST":  
        form = SocialHistoryForm(request.POST, instance=socialhistory)  
        if form.is_valid():  
            try:  
                form.save()
                messages.success(request, 'New Social History is successfully Updated.!')
                # model = form.instance
                return  redirect('/patient_records/patient-detail/{}'.format(id)) 
            except:  
                messages.error(request, 'failed to Update Social History list')
    return render(request,'patient_records/patient-social-history-list.html',{'form':form,'patient' :patient})

def patientVitalSignUpdate(request , id):
    patient= Patient.objects.get(aadhaarId=id)
    vitalsign= VitalSign.objects.get(patient= patient)

inno-Doctor/patient_records/templates/patient_records/eprescription.html
{% extends 'layouts/default/page.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block content %}
<div class="container mt-4">
    {% for i,j in medicationitems.items %}
        <div class="card my-5 p-2">
            <h3 class="text-center mb-4">Medication Statement Id: {{i}}</h3>
            <div class="container">
            <div class="col-md-12 search-table-col m-4">
                <div class="table-responsive table table-hover table-bordered results">
                    <table class="table table-hover table-bordered">
                        <thead class="bill-header cs">
                            <tr>
                                <th class="text-center" id="trs-hd-1" class="col-lg-1">Medication Item</th>
                                <th class="text-center" id="trs-hd-2" class="col-lg-1">Name</th>
                                <th class="text-center" id="trs-hd-3" class="col-lg-1">Form</th>
                                <th class="text-center" id="trs-hd-4" class="col-lg-1">Category</th>
                                <th class="text-center" id="trs-hd-5" class="col-lg-1">Unit of Prescription</th>
                                <th class="text-center" id="trs-hd-6" class="col-lg-1">Batch Id</th>
                                <th class="text-center" id="trs-hd-7" class="col-lg-1">Expiry</th>
                                <th class="text-center" id="trs-hd-8" class="col-lg-1">Dose Amount</th>
                                <th class="text-center" id="trs-hd-9" class="col-lg-1">Dose Duration</th>
                                <th class="text-center" id="trs-hd-10" class="col-lg-1">Dose Unit</th>
                                <th class="text-center" id="trs-hd-11" class="col-lg-1">Dose Frequency</th>
                                <th class="text-center" id="trs-hd-12" class="col-lg-1">Dose Interval</th>
                                <th class="text-center" id="trs-hd-13" class="col-lg-1">Dose Specific Timings</th>
                                <th class="text-center" id="trs-hd-14" class="col-lg-1">Route</th>
                                <th class="text-center" id="trs-hd-15" class="col-lg-1">Body Site</th>
                            </tr>
                        </thead>
                        <tbody>
                            </tr>
                            {% for item in j %}
                                {%if item%}
                                <tr>
                                    <td  class="text-center">{{item.medication_item}}</td>
                                    <td  class="text-center">{{item.name}}</td>
                                    <td  class="text-center">{{item.form}}</td>
                                    <td  class="text-center">{{item.category}}</td>
                                    <td  class="text-center">{{item.unit_of_prescription}}</td>
                                    <td  class="text-center">{{item.batch_id}}</td>
                                    <td  class="text-center">{{item.expiry}}</td>
                                    <td  class="text-center">{{item.dose_amount}}</td>
                                    <td  class="text-center">{{item.dose_duration}}</td>
                                    <td  class="text-center">{{item.dose_unit}}</td>
                                    <td  class="text-center">{{item.dose_frequency}}</td>
                                    <td  class="text-center">{{item.dose_interval}}</td>
                                    <td  class="text-center">{{item.dose_specific_timing}}</td>
                                    <td  class="text-center">{{item.route}}</td>
                                    <td  class="text-center">{{item.body_site}}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            </div>
        </div>
    {% endfor %}
</div>
<!--<div class="container-fluid" style="text-align: center;">-->
<!--     <a type="button" class="btn btn-danger" href="/patient_records/patient-detail/{{aadhaarId}}">🔙</a><h2 class="d-inline align-top">Patient Medical Statement </h2>-->
<!--        <hr>-->
<!--        {% for i,j in medicationitems.items %}-->
<!--        <div class="my-2">-->
<!--            <h6> Medication Statement Id:{{i}}</h6>-->
<!--&lt;!&ndash;            {{ i }}&ndash;&gt;-->
<!--            <div class= "text-*-center small"  >-->
<!--                        <div class="container-fluid">-->
<!--                            <table class="table table-striped table-responsive fixed-table-body">-->
<!--                                <thead class="center-block">-->
<!--                                  <tr>-->

<!--                                    <th scope="col">medication_item</th>-->
<!--                                    <th scope="col">Name</th>-->
<!--                                    <th scope="col">Form</th>-->
<!--                                    <th scform-label-->
<!--form-label-->
<!--form-label-->
<!--form-labelope="col">category</th>-->
<!--                                    <th scope="col">unit_of_presecription</th>-->
<!--                                    <th scope="col">batch_id</th>-->
<!--                                    <th scope="col">expiry</th>-->
<!--                                    <th scope="col">dose_amount</th>-->
<!--                                    <th scope="col">dose_duration</th>-->
<!--                                    <th scope="col">dose_unit</th>-->
<!--                                    <th scope="col">dose_frequency</th>-->
<!--                                    <th scope="col">dose_interval</th>-->
<!--                                    <th scope="col">dose_specific_timing</th>-->
<!--                                    <th scope="col">route</th>-->
<!--                                    <th scope="col">body_site</th>-->
<!--                                </tr>-->
<!--                                </thead>-->
<!--                                <tbody>-->
<!--                            {% for item in j %}-->
<!--                                {% if item %}-->
<!--                                    <tr>-->
<!--                                        <td scope="row">{{item.medication_item}}</td>-->
<!--                                        <td scope="row">{{item.name}}</td>-->
<!--                                        <td scope="row">{{item.form}}</td>-->
<!--                                        <td scope="row">{{item.category}}</td>-->
<!--                                        <td scope="row">{{item.unit_of_prescription}}</td>-->
<!--                                        <td scope="row">{{item.batch_id}}</td>-->
<!--                                        <td scope="row">{{item.expiry}}</td>-->
<!--                                        <td scope="row">{{item.dose_amount}}</td>-->
<!--                                        <td scope="row">{{item.dose_duration}}</td>-->
<!--                                        <td scope="row">{{item.dose_unit}}</td>-->
<!--                                        <td scope="row">{{item.dose_frequency}}</td>-->
<!--                                        <td scope="row">{{item.dose_interval}}</td>-->
<!--                                        <td scope="row">{{item.dose_specific_timing}}</td>-->
<!--                                        <td scope="row">{{item.route}}</td>-->
<!--                                        <td scope="row">{{item.body_site}}</td>-->
<!--                                  </tr>-->
<!--                                    {% endif %}-->
<!--                                  {% endfor %}-->
<!--                                </tbody>-->
<!--                            </table>-->
<!--                        </div>-->
<!--                </div>-->

<!--            <hr>-->
<!--    {% endfor %}-->
<!--</div>-->
{% endblock %}

inno-Doctor/patient_records/templates/patient_records/form.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

<div class="container" style="width:50%; margin-top: 5%; margin-bottom:5%;  ">

<div class="card-body">
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <a type="button" class="btn btn-danger" href="/patient_records/patient-detail/{{aadhaarId}}">Cancel</a>
            <button type="submit" class="btn btn-success" value="save">Add Problems</button>
        </form>
    </div>
</div>
</div>

inno-Doctor/patient_records/templates/patient_records/genralForm.html
{% extends 'layouts/default/page.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% block title %}problem-list{% endblock title %}
{% block content %}
<div class="container" style="width:50%; padding-top: 10px; border-radius: 25px; border: 2px solid black; margin-bottom:5%;  ">

 {% comment %} {% include 'patient_records/form.html'  with aadhaarId=patient.aadhaarId  form=form%} {% endcomment %}
 {% include 'patient_records/table.html'  with aadhaarId=patient.aadhaarId  form=form%}

</div>
{% endblock content %}

inno-Doctor/patient_records/templates/patient_records/patient-check.html
{% extends 'layouts/default/page.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %}patient-check{% endblock title %}
{% block content %}

<div class="container">
    <form role="form" class="text-start" action="{% url 'patient_records:patient_details' %}" method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
        <section class="py-7">
          <div class="container">
            <div class="row justify-space-between py-2">
              <div class="col-lg-4 mx-auto">
                <div class="input-group input-group-dynamic mb-4">
                  <span class="input-group-text"><i class="fas fa-search" aria-hidden="true"></i></span>
                  <input class="form-control" name="aadhaarId" placeholder="Enter Patient Aadhar No" type="number" maxlength="12" pattern=".{12}">
                </div>
              </div>
            </div>
          </div>
        </section>
    </form>

    <h2 class="text-center mb-4">Recent Patient Records</h2>
    <div class="col-md-12 search-table-col m-4">
        <div class="table-responsive table table-hover table-bordered results">
            <table class="table table-hover table-bordered">
                <thead class="bill-header cs">
                    <tr>
                        <th class="text-center" id="trs-hd-1" class="col-lg-2">Patient Name</th>
                        <th class="text-center" id="trs-hd-2" class="col-lg-2">Aadhar No.</th>
                        <th class="text-center" id="trs-hd-3" class="col-lg-2">Date of Birth</th>
                        <th class="text-center" id="trs-hd-4" class="col-lg-1">Gender</th>
                        <th class="text-center" id="trs-hd-5" class="col-lg-1">Action</th>
                    </tr>
                </thead>
                <tbody>
                    </tr>
                    {% for patient in patients %}
                    <tr>
                        <td class="text-center">{{ patient.aadhaarId}}</td>
                        <td class="text-center">{{ patient.name }}</td>
                        <td class="text-center">{{ patient.date_of_birth }}</td>
                        <td class="text-center">{{ patient.gender }}</td>
                        <td class="text-center">
                            <a href="/patient_records/patient-detail/{{ patient.aadhaarId }}"><i class="fas fa-edit"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<!--<div class="container" style="width:50%; margin-top: 5%; padding-top: 10px; border-radius: 25px; border: 2px solid black; margin-bottom:5%;">-->
<!--<div class="card-body">-->
<!--    <h4>Recent Patient Records</h4>-->
<!--    <table class="table">-->
<!--        <thead>-->
<!--            <tr>-->
<!--                <th scope="col">Patient Name</th>-->
<!--                <th scope="col">Aadhaar Id</th>-->
<!--                <th scope="col">Date Of Birth</th>-->
<!--                <th scope="col">Gender</th>-->
<!--                <th scope="col"></th>-->
<!--                <th scope="col"></th>-->
<!--            </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--            {% for patient in patients %}-->
<!--            <tr>-->
<!--                <td>{{ patient.name }}</td>-->
<!--                <td>{{ patient.aadhaarId }}</td>-->
<!--                <td>{{ patient.date_of_birth }}</td>-->
<!--                <td>{{ patient.gender }}</td>-->
<!--                <td><a type="button" class="btn btn-warning" href="/patient_records/patient-update/{{ patient.aadhaarId }}">✍🏻</a></td>-->
<!--            </tr>-->
<!--            {% endfor %}-->
<!--        </tbody>-->
<!--    </table>-->
<!--    <a type="button" class="btn btn-info" href="#top">scroll up</a>-->
<!--</div>-->

<!--</div>-->

{% endblock %}

inno-Doctor/patient_records/templates/patient_records/patient-medication-item.html
{% extends 'layouts/default/page.html' %}
{% load static %}
{% load bootstrap4 %}
{% load i18n %}
{% block title %}new-medication-item{% endblock title %}
{% block content %}
<div class="container" style="width:50%; padding-top: 10px; border-radius: 25px; border: 2px solid black; margin-bottom:5%;  ">

 {% comment %} {% include 'patient_records/form.html'  with aadhaarId=patient.aadhaarId  form=form%} {% endcomment %}
 {% include 'patient_records/table.html'  with aadhaarId=patient.aadhaarId  form=form%}

</div>
{% endblock content %}

inno-Doctor/patient_records/templates/patient_records/patient-update.html
{% extends 'layouts/default/page.html' %}
{% load static %}
{% load bootstrap4 %}
{% load widget_tweaks %}
{% load i18n %}

{% block content %}

<div class="container">
<form method = "post">
    {% csrf_token %}
    <div class="input-group input-group-outline my-3">
        <label class="form-label-inline w-30">Patient Name:</label>
        {% render_field form.name class="form-control" type="text" %}
    </div>
    <div class="input-group input-group-outline my-3">
        <label class="form-label-inline w-30">Aadhar No:</label>
        {% render_field form.aadhaarId class="form-control" type="number" %}
    </div>
    <div class="input-group input-group-outline my-3">
        <label class="form-label-inline w-30">Gender:</label>
        {% render_field form.gender class="form-control" %}
    </div>
    <div class="input-group input-group-outline my-3">
        <label class="form-label-inline w-30">Date of Birth:</label>
        {% render_field form.date_of_birth class="form-control" type="date" %}
    </div>
    <div class="text-center">
        <button type="submit" value="save" class="btn bg-gradient-info w-40 my-4 mb-2 mx-2">Update</button>
        <a class="btn bg-gradient-danger w-40 my-4 mb-2 mx-2" href="{% url 'patient_records:patient_check' %}">Cancel</a>
    </div>
</form>

</div>
{% endblock %}